# Generated by Django 2.0.1 on 2018-02-12 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_customer_orderitem_orderlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='client',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='OrderList',
        ),
    ]
