# Generated by Django 2.0.1 on 2018-02-13 00:11

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180213_0140'),
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_fullname', models.CharField(max_length=50)),
                ('client_address', models.CharField(max_length=50)),
                ('client_phone_number', models.CharField(max_length=10)),
                ('client_phone_email', models.EmailField(max_length=254)),
                ('orders', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
        ),
    ]
