# Generated by Django 2.0.1 on 2018-02-13 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='client_phone_email',
            new_name='client_email',
        ),
    ]
